/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cloud_logic_custom": [
        {
            "name": "instapostapi",
            "endpoint": "https://j6q1rm0tqh.execute-api.us-east-2.amazonaws.com/local",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
